In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns

In [2]:
df = pd.read_csv('data/raw/nyc_collisions_2021_to_20260327.csv')
print("Load data successfully!!!")

Load data successfully!!!

In [3]:
df.shape

(505949, 29)

In [4]:
df.head(10)

,crash_date,crash_time,latitude,longitude,location,on_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,...,borough,zip_code,off_street_name,cross_street_name,contributing_factor_vehicle_3,vehicle_type_code_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,vehicle_type_code_4,vehicle_type_code_5
0,2021-01-01,20:00,40.833980,-73.826350,"{'latitude': '40.83398', 'longitude': '-73.826...",BRUCKNER EXPRESSWAY,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-01,5:28,40.687300,-73.973656,"{'latitude': '40.6873', 'longitude': '-73.9736...",LAFAYETTE AVENUE,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-01,6:00,NaN,NaN,NaN,WEST SHORE EXPRESSWAY,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-01,19:30,40.882700,-73.892730,"{'latitude': '40.8827', 'longitude': '-73.89273'}",SEDGWICK AVENUE,0.0,0,0,0,...,BRONX,10463.0,VANCORTLANDT AVENUE WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-01,7:40,40.637910,-73.978640,"{'latitude': '40.63791', 'longitude': '-73.978...",CORTELYOU ROAD,0.0,0,0,0,...,BROOKLYN,11218.0,MC DONALD AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-01-01,18:45,40.848630,-73.927620,"{'latitude': '40.84863', 'longitude': '-73.927...",HARLEM RIVER DRIVE,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-01-01,4:51,40.660090,-73.900550,"{'latitude': '40.66009', 'longitude': '-73.900...",NaN,0.0,0,0,0,...,BROOKLYN,11212.0,NaN,582 JUNIUS STREET,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-01-01,16:14,40.705807,-73.931760,"{'latitude': '40.705807', 'longitude': '-73.93...",NaN,0.0,0,0,0,...,BROOKLYN,11237.0,NaN,55 MORGAN AVENUE,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-01-01,22:15,40.663227,-73.931590,"{'latitude': '40.663227', 'longitude': '-73.93...",UTICA AVENUE,0.0,0,0,0,...,NaN,NaN,EAST NEW YORK AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-01-01,12:00,40.671482,-73.882840,"{'latitude': '40.671482', 'longitude': '-73.88...",NaN,0.0,0,0,0,...,BROOKLYN,11208.0,NaN,476 ELTON STREET,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail(10)

,crash_date,crash_time,latitude,longitude,location,on_street_name,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,...,borough,zip_code,off_street_name,cross_street_name,contributing_factor_vehicle_3,vehicle_type_code_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,vehicle_type_code_4,vehicle_type_code_5
505939,2026-03-23,8:00,40.689510,-73.948040,"{'latitude': '40.68951', 'longitude': '-73.948...",MARCY AVE,1.0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505940,2026-03-23,7:56,40.695950,-73.937630,"{'latitude': '40.69595', 'longitude': '-73.937...",LEWIS AVE,1.0,0,1,0,...,BROOKLYN,11206.0,VERNON AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505941,2026-03-23,8:40,40.689920,-73.777890,"{'latitude': '40.68992', 'longitude': '-73.777...",115 AVE,0.0,0,0,0,...,QUEENS,11434.0,MERRICK BLVD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505942,2026-03-23,3:45,NaN,NaN,NaN,TRANS-MANHATTAN EXPRESSWAY,0.0,1,0,0,...,NaN,NaN,AMSTERDAM AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505943,2026-03-23,15:46,40.638620,-73.891045,"{'latitude': '40.63862', 'longitude': '-73.891...",AVENUE M,1.0,0,1,0,...,BROOKLYN,11236.0,E 100 ST,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505944,2026-03-23,20:53,40.636820,-73.902176,"{'latitude': '40.63682', 'longitude': '-73.902...",AVENUE K,2.0,0,0,0,...,BROOKLYN,11236.0,REMSEN AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505945,2026-03-23,10:47,40.803123,-73.940440,"{'latitude': '40.803123', 'longitude': '-73.94...",E 122 ST,1.0,0,1,0,...,MANHATTAN,10035.0,PARK AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505946,2026-03-23,7:50,40.585922,-74.105255,"{'latitude': '40.585922', 'longitude': '-74.10...",JEFFERSON AVE,1.0,0,0,0,...,STATEN ISLAND,10306.0,RICHMOND RD,NaN,Unspecified,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
505947,2026-03-23,7:56,40.622765,-73.979360,"{'latitude': '40.622765', 'longitude': '-73.97...",54 ST,1.0,0,1,0,...,BROOKLYN,11204.0,20 AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505948,2026-03-23,9:45,40.698746,-73.994720,"{'latitude': '40.698746', 'longitude': '-73.99...",NaN,0.0,0,0,0,...,BROOKLYN,11201.0,NaN,31 PINEAPPLE ST,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 505949 entries, 0 to 505948
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   crash_date                     505949 non-null  str
 1   crash_time                     505949 non-null  str
 2   latitude                       472730 non-null  float64
 3   longitude                      472730 non-null  float64
 4   location                       472730 non-null  str
 5   on_street_name                 363058 non-null  str
 6   number_of_persons_injured      505948 non-null  float64
 7   number_of_persons_killed       505949 non-null  int64
 8   number_of_pedestrians_injured  505949 non-null  int64
 9   number_of_pedestrians_killed   505949 non-null  int64
 10  number_of_cyclist_injured      505949 non-null  int64
 11  number_of_cyclist_killed       505949 non-null  int64
 12  number_of_motorist_injured     505949 non-null  int64
 13  number_of_motorist_killed      505949 non-null  int64
 14  contributing_factor_vehicle_1  502683 non-null  str
 15  collision_id                   505949 non-null  int64
 16  vehicle_type_code1             498204 non-null  str
 17  contributing_factor_vehicle_2  386235 non-null  str
 18  vehicle_type_code2             334245 non-null  str
 19  borough                        354273 non-null  str
 20  zip_code                       354201 non-null  float64
 21  off_street_name                254453 non-null  str
 22  cross_street_name              142886 non-null  str
 23  contributing_factor_vehicle_3  46627 non-null   str
 24  vehicle_type_code_3            43306 non-null   str
 25  contributing_factor_vehicle_4  12365 non-null   str
 26  contributing_factor_vehicle_5  3722 non-null    str
 27  vehicle_type_code_4            11699 non-null   str
 28  vehicle_type_code_5            3572 non-null    str
dtypes: float64(4), int64(8), str(17)
memory usage: 216.3 MB

In [7]:
missing_value = df.isnull().sum()
print(f"Check missing value:\n{missing_value}")

Check missing value:
crash_date                            0
crash_time                            0
latitude                          33219
longitude                         33219
location                          33219
on_street_name                   142891
number_of_persons_injured             1
number_of_persons_killed              0
number_of_pedestrians_injured         0
number_of_pedestrians_killed          0
number_of_cyclist_injured             0
number_of_cyclist_killed              0
number_of_motorist_injured            0
number_of_motorist_killed             0
contributing_factor_vehicle_1      3266
collision_id                          0
vehicle_type_code1                 7745
contributing_factor_vehicle_2    119714
vehicle_type_code2               171704
borough                          151676
zip_code                         151748
off_street_name                  251496
cross_street_name                363063
contributing_factor_vehicle_3    459322
vehicle_type_code_3              462643
contributing_factor_vehicle_4    493584
contributing_factor_vehicle_5    502227
vehicle_type_code_4              494250
vehicle_type_code_5              502377
dtype: int64

In [8]:
duplicate_value = df.duplicated().sum()
print(f"Check duplicated values: {duplicate_value}")

Check duplicated values: 21

In [9]:
df.describe()

,latitude,longitude,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,collision_id,zip_code
count,472730.000000,472730.000000,505948.000000,505949.000000,505949.000000,505949.000000,505949.000000,505949.000000,505949.000000,505949.000000,5.059490e+05,354201.000000
mean,40.214187,-72.994893,0.535684,0.002769,0.091679,0.001255,0.051968,0.000239,0.371575,0.001140,4.634338e+06,10886.229166
std,4.523190,8.209412,0.834270,0.055369,0.304671,0.036232,0.226012,0.015463,0.810432,0.036938,1.461057e+05,529.837154
min,0.000000,-74.254960,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.073803e+06,10000.000000
25%,40.664074,-73.965981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.507825e+06,10455.000000
50%,40.713226,-73.920840,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.634350e+06,11208.000000
75%,40.774170,-73.865470,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.760861e+06,11237.000000
max,40.912884,0.000000,40.000000,5.000000,19.000000,4.000000,3.000000,1.000000,40.000000,5.000000,4.887622e+06,12345.000000